### ISSUE TITLE
Tuxclocker displays incorrect data

### ISSUE THREAD

**Issue by andreas-R17** [Lurkki14/tuxclocker#15]
Program displays incorrect data Core and Memory Utilization on GTX 650.

Linux: 4.15 (x86_64)
Qt: 5.11.2
Driver: 410.78

[https://i.imgur.com/YbAV2uM.jpg](url)

**Comment by Lurkki14** [comment]
Are they readable by nvidia-smi: `nvidia-smi --query-gpu=utilization.memory --format=csv` `nvidia-smi --query-gpu=utilization.gpu --format=csv` ? Either way I need to make a better way to hide unavailable readings.

**Comment by andreas-R17** [comment]
~ $ nvidia-smi --query-gpu=utilization.memory --format=csv
utilization.memory [%]
[Not Supported]

~ $ nvidia-smi --query-gpu=utilization.gpu --format=csv
utilization.gpu [%]
[Not Supported]

**Comment by Lurkki14** [comment]
Closing since invalid values shouldn't be displayed in the GUI anymore
