### ISSUE TITLE
Only power limit setting is available

### ISSUE THREAD

**Issue by ArtifTh** [Lurkki14/tuxclocker#19]
Nvidia GTX 1050 Ti
Tuxclocker built from commit 51c594227ad0868d1a7052ba9a88aa7268c39686
```
    Option         "Coolbits" "31"
```
Clock offset settings are available in `nvidia-settings`

**Comment by Lurkki14** [comment]
Fixed in https://github.com/Lurkki14/tuxclocker/pull/20/commits/20a3534632dc233160660afb1dd6fb1fab0d867d
