### ISSUE TITLE
MVC model

### ISSUE THREAD

**Issue by ppetraki** [Lurkki14/tuxclocker#26]
The current design is too tightly coupled to allow for multiple, different GPUs, to be inspected on the same machine.

A MVC model with delegates for rendering would address this issue.

**Comment by Lurkki14** [comment]
Agreed, my current plan is to make each GPU offer a tree of its sensors and tunables whose interactions can be abstracted into one interface. Should get rid of the inflexibilities like having a separate editor for AMD's pstates.

**Comment by Lurkki14** [comment]
Has been implemented in 1.0
