### ISSUE TITLE
stub api to build without vendor specific libs

### ISSUE THREAD

**Issue by ppetraki** [Lurkki14/tuxclocker#27]
The current state of affairs is to compile the project specifically for a single type of GPU.

It's conceivable that:
1) GPUS come and go
2) a mix of GPUs can exist on a system
3) GPGPUs can also exist

To that end. If the project where refactored to stub out the vendor specific calls and then use dlopen to load the appropriate library, when a suitable PCI device is detected. The program could flexibly support any number or combination of GPU vendors.

A "dummy" gpu backend would also be ideal for testing the interface. This would easily fall out as part of the refactoring.

**Comment by Lurkki14** [comment]
I'm aware of this design issue and it's being worked on

**Comment by Lurkki14** [comment]
I've implemented most of this in tuxclocker-next branch, sans some sanity checks when it comes to loading modules.

**Comment by Lurkki14** [comment]
Has been implemented in 1.0
