### ISSUE TITLE
Custom fan curve does not save

### ISSUE THREAD

**Issue by NoXPhasma** [Lurkki14/tuxclocker#3]
The custom fan curve doesn't get saved for me. I set my own fan curve, then press save and when I open up the fan curve window again, it's empty.  It's not only the window which is empty, when I apply the changes of the fan curve in the app, it will hold the Fans at 0%.

OS: Linux Mint 19.1 Tessa
GPU: GeForce GTX 1080 (415.27)
Coolbits 28
Tuxlocker version 0.1.0

**Comment by Lurkki14** [comment]
Is this related to the issue you closed?

**Comment by NoXPhasma** [comment]
No, it's not. This still happens with writeable config file. I checked that double.

The config file actually gets the changes made on the mesh, but neither does it applied nor is it shown on the mesh when reopened. Current config file:

```
[%General]
currentProfile=test
latestUUID=GPU-83ec8765-92ac-8f79-c841-881477b8e35a

[New%20Profile]
GPU-83ec8765-92ac-8f79-c841-881477b8e35a\fanControlMode=0
GPU-83ec8765-92ac-8f79-c841-881477b8e35a\memoryClockOffset=0
GPU-83ec8765-92ac-8f79-c841-881477b8e35a\xpoints="0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 67, "
GPU-83ec8765-92ac-8f79-c841-881477b8e35a\ypoints="0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 31, 78, "
isProfile=true

[test]
GPU-83ec8765-92ac-8f79-c841-881477b8e35a\fanControlMode=2
GPU-83ec8765-92ac-8f79-c841-881477b8e35a\memoryClockOffset=0
GPU-83ec8765-92ac-8f79-c841-881477b8e35a\xpoints="0, 0, 0, 0, 0, 0, 1, 45, 71, "
GPU-83ec8765-92ac-8f79-c841-881477b8e35a\ypoints="0, 0, 0, 0, 0, 0, 49, 58, 81, "
isProfile=true
```

**Comment by Lurkki14** [comment]
Are other settings being loaded correctly?

**Comment by NoXPhasma** [comment]
Yes, other changes are stored and loaded properly. Even on a app restart.

However I just found out that when I choose an offset for memory clock and switch profiles (Profile 1 (+100), Profile 2 (0)) from Profile 1 to 2 and back to 1, it shows 200 instead of 100. It actually doubles whatever is used, if it's -16 it makes it to -32. And so on.

**Comment by Lurkki14** [comment]
Fixed with https://github.com/Lurkki14/tuxclocker/commit/21a4a0895a567c8346ec8cd97df2a428673de2c3
