### ISSUE TITLE
DRM version being misread ? 

### ISSUE THREAD

**Issue by MasterCATZ** [Lurkki14/tuxclocker#31]
using git checkout pstatetest
I have  Power Cap control but no FAN / GPU / MEMORY control

sudo ./tuxclocker 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QMetaObject::connectSlotsByName: No matching signal for on_newProfile_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_newProfile_closed()
QMetaObject::connectSlotsByName: No matching signal for on_editProfile_closed()
amdgpu_device_initialize: DRM version is **1.6.0** but this driver is only compatible with 3.x.x.

#DRI_PRIME=1 glmark2
=======================================================
    glmark2 2014.03+git20150611.fa71af2d
=======================================================
    OpenGL Information
    GL_VENDOR:     X.Org
    GL_RENDERER:   AMD Radeon R9 200 Series (HAWAII, DRM **3.33.0**, 5.3.8-050308-generic, LLVM 9.0.0)
    GL_VERSION:    4.5 (Compatibility Profile) Mesa 19.3.0-devel (git-ff6e148 2019-10-29 bionic-oibaf-ppa)

**Comment by Lurkki14** [comment]
That error gets raised when the program is iterating through all GPU device files so it shouldn't matter. Are you using something newer than the Vega series?

**Comment by Lurkki14** [comment]
Closing as outdated
