### ISSUE TITLE
Profiles are not saved on exit

### ISSUE THREAD

**Issue by NoXPhasma** [Lurkki14/tuxclocker#4]
Profiles are not saved on exit of the app. Neither the changes done to the default profile, nor new added profiles.

Is there a config file, tuxlocker creates, I can check?

OS: Linux Mint 19.1 Tessa
GPU: GeForce GTX 1080 (415.27)
Coolbits 28
Tuxlocker version 0.1.0

**Comment by Lurkki14** [comment]
Check if $HOME/.config/tuxclocker.conf exists and post it here.

**Comment by NoXPhasma** [comment]
Thanks, this was actually a problem on my side. I've had tuxlocker in a previous version running as root and by that the config file was now written with root user rights. After I've deleted the file I was able to store the profiles.

Closed.
