### ISSUE TITLE
Voltage Control on GTX 1060 6GB Greyed Out

### ISSUE THREAD

**Issue by Abh15h3k** [Lurkki14/tuxclocker#40]
I have a Zotac GTX 1060 6GB Mini. 
I have set cool bits to 31.
Voltage Offset is greyed Out.
This is on Arch Linux. Installed through the AUR. same issue on both tuxclocker and tuxclocker-git.

**Comment by Lurkki14** [comment]
Nvidia doesn't allow for overvolting on the 1000-series through their library that TuxClocker uses. So unless there is some alternate method to set it it's not within my reach.
