### ISSUE TITLE
Unable to adjust

### ISSUE THREAD

**Issue by zkbutt** [Lurkki14/tuxclocker#46]
Unable to adjust, hint

QMetaObject::connectSlotsByName: No matching signal for on_newProfile_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_newProfile_closed()
QMetaObject::connectSlotsByName: No matching signal for on_editProfile_closed()
QMetaObject::connectSlotsByName: No matching signal for on_newProfile_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_newProfile_closed()
QMetaObject::connectSlotsByName: No matching signal for on_editProfile_closed()

**Comment by zkbutt** [comment]
Unable to switch mode

**Comment by Lurkki14** [comment]
Closed due to not enough information
