### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by All3xJ** [Lurkki14/tuxclocker#47]
```
$ sudo tuxclocker 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QMetaObject::connectSlotsByName: No matching signal for on_newProfile_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_newProfile_closed()
QMetaObject::connectSlotsByName: No matching signal for on_editProfile_closed()
Segmentation fault
```
I have Ryzen 3500U with integrated gpu

**Comment by rayphee** [comment]
Seems to be related to this issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/2424

I modified `amd.cpp:29` to be `fd = open(path, O_RDWR | O_CLOEXEC);` and tuxclocker opens without a segfault. I'm running this on a 5700XT so this _may_ not work on your GPUs, but I doubt it because the original link appears to solve for Polaris GPUs. Either way, lmk if it works on your systems.

**Comment by Hansard** [comment]
I am on a 5700XT, and I still get the error. But perhaps I am doing something wrong.

tuxclocker                                                                                        SEGV ✘ 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QMetaObject::connectSlotsByName: No matching signal for on_newProfile_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_newProfile_closed()
QMetaObject::connectSlotsByName: No matching signal for on_editProfile_closed()
zsh: segmentation fault (core dumped)  tuxclocker
    ~  sudo tuxclocker                                                                                   SEGV ✘ 
[sudo] password for christopher: 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QMetaObject::connectSlotsByName: No matching signal for on_newProfile_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_newProfile_closed()
QMetaObject::connectSlotsByName: No matching signal for on_editProfile_closed()
zsh: segmentation fault  sudo tuxclocker

Is there a solution?

**Comment by alexdelorenzo** [comment]
Running into this problem, as well. Same segmentation fault and error logs.

**Comment by Lurkki14** [comment]
Closing as outdated
