### ISSUE TITLE
ninja: build stopped: subcommand failed

### ISSUE THREAD

**Issue by begin-theadventure** [Lurkki14/tuxclocker#55]
[54/55] Compiling C++ object src/tuxclocker-qt/tuxclocker-qt.p/Utils.cpp.o
ninja: build stopped: subcommand failed.

**Comment by Lurkki14** [comment]
That doesn't help much, please post the full error.

**Comment by begin-theadventure** [comment]
[build.txt](https://github.com/Lurkki14/tuxclocker/files/12738170/build.txt)

**Comment by Lurkki14** [comment]
Strange, can't reproduce with those build options and g++ 12.3.0. Try building without custom meson options and putting `#include <cstdint>` before this include https://github.com/Lurkki14/tuxclocker/blob/cpplib/src/tuxclocker-qt/widgets/FlagEditor.hpp#L7

**Comment by Lurkki14** [comment]
So what was the fix? Was it to build without custom meson flags?

**Comment by Lurkki14** [comment]
Anyone having this issue, try running `git submodule update --remote --merge` and build afterwards, see if it fixes this.

**Comment by xcoldfyrex** [comment]
> Anyone having this issue, try running `git submodule update --remote --merge` and build afterwards, see if it fixes this.

Confirming this allowed me to compile successfully.

**Comment by Lurkki14** [comment]
Fixed with https://github.com/Lurkki14/tuxclocker/commit/5760567fe99429445deb022587b75580aa555d8c
