### ISSUE TITLE
Build error with new python3-hwdata dep

### ISSUE THREAD

**Issue by pallaswept** [Lurkki14/tuxclocker#68]
I managed with some difficulty to get the new dependency to package, but then tuxclocker generates an error:

```
Program python3 (hwdata) found: YES (/usr/bin/python3) modules: hwdata

src/plugins/meson.build:20:3: ERROR: Unknown statement.
```

**Comment by pallaswept** [comment]
Even if you disable the thing with 
```
    -Drequire-python-hwdata=false
```
If the dependency is present then it generates this error.

**Comment by Lurkki14** [comment]
Thanks for the report, somehow missed this. What went wrong was https://github.com/Lurkki14/tuxclocker/blob/master/src/plugins/meson.build#L20 being on a separate line. Fixed with https://github.com/Lurkki14/tuxclocker/commit/5f7137e7785a1872bf62c7d353f1d3081d689c12
