### ISSUE TITLE
Become part of KDE apps?

### ISSUE THREAD

**Issue by eszlari** [Lurkki14/tuxclocker#72]
TuxClocker isn't available and thus not easily installable on most Linux distribution at the moment.

One way to solve this problem could be to become part of a bigger umbrella project. Since TuxClocker uses Qt it seems that the KDE project would be a good fit.

https://community.kde.org/Incubator

**Comment by Lurkki14** [comment]
It's up to distros to package the software, and being a part of KDE doesn't change that. Sure, it might get more visibility but there's other ways to get that. If TuxClocker isn't packaged on your distro you should ask the distro to do so.

**Comment by eszlari** [comment]
> It's up to distros to package the software, and being a part of KDE doesn't change that. 

If TuxClocker became part of the official [KDE Gear](https://kde.org/announcements/gear) collection, every distro that provides KDE would package it.

But there are also other advantages:
* CI (test build server, static analysis, packaging, automatic release management)
* translation system with a lot of contributors & languages
* other KDE develpers help with porting to newer Qt APIs
* KWin contributors know about kernel APIs, it's likely they would provide patches
* [bus factor](https://en.wikipedia.org/wiki/Bus_factor) > 1
