### ISSUE TITLE
Parametrize on FAN1 and FAN2 not working

### ISSUE THREAD

**Issue by koloved** [Lurkki14/tuxclocker#74]
Nvidia gpu 3090
i tried to set curve few times like from 47% min to 67 Celsius , and then to the 85C 100%

3 points only

**Comment by Lurkki14** [comment]
Need a bit more information. Does setting a single value for the fan speeds work? What does this look like in the GUI?

**Comment by Lurkki14** [comment]
Closing due to not enough information to know what the issue is.
