### ISSUE TITLE
[Question][Request] Are both dbus-daemon and tuxclockerd needed for frontend?

### ISSUE THREAD

**Issue by h0x32** [Lurkki14/tuxclocker#78]
Hello,

is running both tuxclockerd and dbus-daemon needed for using the frontend
and if so, can you please add a check in the frontend to display a warning message?

**Comment by Lurkki14** [comment]
Your system likely has a DBus session already running, so it's not strictly needed. What are you doing exactly that the README doesn't cover?
> can you please add a check in the frontend to display a warning message?

There already is a warning message in the terminal when the GUI is unable to connect to `tuxclockerd`.

**Comment by h0x32** [comment]
yes but would it be possible to have one in the gui?
just to warn people that there is a service component of this software

do not get me wrong, i am a maintainer of the [tuxclocker-git](https://aur.archlinux.org/packages/tuxclocker-git) aur package and i have created two systemd services
one called tuxclockerd and another called tuxclockerd-dbus
and i have added an env file for both systemd to read from which contains:

DBUS_VERBOSE=1
DBUS_SYSTEM_BUS_ADDRESS=unix:path=/tmp/tuxclocker-dbus-socket
TUX_DBUS_CONF_FILE=/etc/tuxclocker-dbusconf.conf
LD_LIBRARY_PATH=/usr/lib/tuxclocker

however i won't be enabling both systemd services by default and i am leaving it to the user to enable them

but i have included a warning message post install for people who might use the terminal 
'Please do not forget to enable and start systemd services "systemctl enable --now tuxclockerd-dbus tuxclockerd"'

for the sake of the users, it would be also great to include some sort of a GUI warning message to warn the users that other components the software relies on are not running

it would also be great to add checks for the existing of the daemon (tuxclockerd)
and display another gui warning message for that case

**Comment by SeongGino** [comment]
Ditto. As it is, out of the box without the maintainer putting that info out there, I open up tuxclocker and only see an almost entirely empty window with no other feedback. It feels like the app is broken more than user error.

@h0x32, so you're the maintainer of the AUR package! Just as a note, something like a post-packaging message should really be inserted as a `post-install` echo in a `$pkgname.install` file, because I also almost missed that message just now from building.

**Comment by h0x32** [comment]
> Ditto. As it is, out of the box without the maintainer putting that info out there, I open up tuxclocker and only see an almost entirely empty window with no other feedback. It feels like the app is broken more than user error.
> 
> @h0x32, so you're the maintainer of the AUR package! Just as a note, something like a post-packaging message should really be inserted as a `post-install` echo in a `$pkgname.install` file, because I also almost missed that message just now from building.

yes my bad, i just realized the echo messages will be burred deep in the terminal and not a lot of people will have a chance to look at them
thank you for letting me know, i will add the notes in post_install

**Comment by h0x32** [comment]
@SeongGino 

post install and post upgrades notes have been added to the aur package

**Comment by Lurkki14** [comment]
https://github.com/Lurkki14/tuxclocker/commit/ee1159436b347fd8089f6b71a12dda9a2e906ce3#diff-b581f578da188b8900c37286b849d654dfce9b0c0d3cfa2b4b1ff6e9d5fedbf6

**Comment by h0x32** [comment]
thank you, i will test it and provide feedback

**Comment by h0x32** [comment]
it is perfect, thank you
![image](https://github.com/Lurkki14/tuxclocker/assets/42139189/9be85aa4-3e90-4e78-a892-593cd882e904)
