### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by DanielRios549** [Lurkki14/tuxclocker#9]
Are there any packages for this program? If not, what are the packages I need to install for compile it? I install git, qt5-default, g++, libqt5x11extras5-dev, nvidia-sm and nvidia-settings, but it does not compile due to a error on nvctrl.

**Comment by Lurkki14** [comment]
Some distros package libxnvctrl in separate packages where the development package (usually *-dev) contains the headers it needs, so you'll need to install that.

**Comment by BlinCT** [comment]
I immediately have a question, why did you not pack this program into a snap package and put it in a store?
This would simplify access to the program and installation. And it would not be necessary for the user to compile it for himself.
It seems that the developers all want their software to be more common, but there is no convenience.

**Comment by DanielRios549** [comment]
I have to compile it before packing into a package, but I only know how to pack into a deb and an AppImage package, I can do that if I had the program running on my system.

**Comment by DanielRios549** [comment]
I compiled the program with some warnings, the problem is that I don't have too much experience, so I compiled it on a live Kubuntu 18.04.1 inside a VM to do not affect my system (is that right, can I do that inside a VM?), and it does not run in that VM, it has a  core dump error, so I copied the file installed in /opt it to my host and it runs, but with some features not working properly. Everything works except for these options on the first tab, Power Limit is the only that works in this tab

![image](https://user-images.githubusercontent.com/11152535/53169267-894a1180-35bb-11e9-8525-dbebae392852.png)

**Comment by Lurkki14** [comment]
The sliders are disabled due to those features being read-only on your system (aka coolbits not being set). Since the issue you opened this for was resolved, I'll close this one. Feel free to open another if other issues arise.

**Comment by DanielRios549** [comment]
How do I enable these coolbits?
